### ISSUE TITLE
[FEATURE REQUEST] MySQL loader (64-bit)

### ISSUE THREAD

**Issue by thareh** [bmx-ng/database.mod#1]
Jolly good, sir!

I'd like to formally make a request for a MySQL loader (64-bit) and would be most pleasantly surprised if one would be made.

I thank thee,
Thareh

**Comment by woollybah** [comment]
Sure can do.
People are still using MySQL then? 🚀 

Unicode stuff is always fun..

**Comment by thareh** [comment]
Awesome! 😄 
Oh yes, I'm using MariaDB though but as far as I know it's MySQL compatible - but perhaps there is a dedicated MariaDB driver as well?

Thanks!

**Comment by GWRon** [comment]
Think mariadb works too...

**Comment by thareh** [comment]
Wasn't an UTF-8 issue I think, but I inserted empty strings into the database and they appear as scrambled characters.
