### ISSUE TITLE
[FR] PostgreSQL

### ISSUE THREAD

**Issue by thareh** [bmx-ng/database.mod#10]
Good day,

It'd be a nice addition with a PostgreSQL module.

Thanks!

**Comment by woollybah** [comment]
Funnily enough, I was looking at that today...

**Comment by thareh** [comment]
It's fate! May the lord guideth us to an awesome module. Amen.

I've read it's faster and more strict than MariaDB which sounds good, so been wanting to try it out for a while😄

**Comment by woollybah** [comment]
Added
